name: Despliegue Frontend a Amazon ECR

on:
  push:
    branches: [ "deploy" ]

env:
  AWS_REGION: us-east-1                 
  ECR_REPOSITORY: front-despacho-innovatech 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Iniciar sesion en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir imagen y subir a la nube
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Desplegar en EC2 vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}        # La IP de la instancia específica
          username: ubuntu                    # Usuario por defecto en AWS Academy
          key: ${{ secrets.EC2_SSH_KEY }}     # Tu archivo .pem
          script: |
            # 1. Entrar a la carpeta del proyecto en la EC2
            cd /home/ubuntu/nombre-de-tu-carpeta 
            
            # 2. Autenticar Docker con ECR dentro del servidor
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            
            # 3. Descargar la imagen nueva y reiniciar el servicio
            docker compose pull
            docker compose up -d
