name: Despliegue Frontend a EKS

on:
  push:
    branches: [ "deploy" ]

env:
  AWS_REGION: us-east-1
  # Se especifica el repositorio exacto de ECR configurado para el frontend
  ECR_REPOSITORY: examen-front
  # Se especifica el nombre del clúster de Amazon EKS
  EKS_CLUSTER_NAME: cluster-examen

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Iniciar sesion en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir imagen y subir a la nube
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        # Se compila la imagen con los archivos estáticos de la interfaz y se transfiere al registro
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Conectar al Cluster EKS
        # Se establece la conexión con el plano de control del clúster actualizando el archivo kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Desplegar en Kubernetes
        # Se garantiza la existencia del espacio de nombres y se aplican los manifiestos de la capa de presentación
        run: |
          kubectl create namespace examen --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/frontend-deployment.yaml -n examen
          kubectl apply -f k8s/frontend-service.yaml -n examen
          kubectl apply -f k8s/frontend-hpa.yaml -n examen
          kubectl rollout restart deployment front-despacho-deployment -n examen
